### ISSUE TITLE
dead links

### ISSUE THREAD

**Issue by shawnharmsen** [ethresearch/eth-wiki#5]
Hello, just going through and checking for typos and dead links

Dead links:
1. home
https://eth.wiki/CC0-license#list-of-contributors

![license](https://user-images.githubusercontent.com/5439924/59697855-315f9800-91b4-11e9-9482-99fe37a09d16.PNG)

2. evm
https://eth.wiki/contributing.md

![evm](https://user-images.githubusercontent.com/5439924/59698330-13defe00-91b5-11e9-8df4-554dc0d94c12.PNG)

3. evm
https://eth.wiki/evm/all

![evm2](https://user-images.githubusercontent.com/5439924/59698414-412bac00-91b5-11e9-9179-735d0cd62b4d.PNG)

**Comment by virgil** [comment]
Sure go ahead and directly edit these.  Just login via Github and click the edit button.
